Add tape_read function.

diff --git a/bin/oxbackup b/bin/oxbackup
--- a/bin/oxbackup
+++ b/bin/oxbackup
@@ -246,9 +246,25 @@ function tape_write
 		$DD $* of=/dev/null
 	else
 		if [[ -n "$REMOTE" ]]; then
-			$RSH $DUMP_HOST "$DD $* of=$DUMP_DEVICE "
+			$RSH $DUMP_HOST "$DD $* of=$DUMP_DEVICE"
 		else
 			$DD $* of=$DUMP_DEVICE
+		fi
+	fi
+}
+
+# Read data from tape using dd
+# $* = dd directives
+function tape_read
+{
+	if (( NO_TAPE > 0 )); then
+		echo "--> NO TAPE: aborting"
+		exit 1
+	else
+		if [[ -n "$REMOTE" ]]; then
+			$RSH $DUMP_HOST "$DD $* if=$DUMP_DEVICE"
+		else
+			$DD $* if=$DUMP_DEVICE
 		fi
 	fi
 }
