Current snapshot of new script, renamed to oxbackup.

diff --git a/bin/oxbackup b/bin/oxbackup
--- a/bin/oxbackup
+++ b/bin/oxbackup
@@ -11,24 +11,33 @@ BASE=$(cd $(dirname $0)/..; pwd)
 LOG_FILE=$BASE/log/backup.log
 TOC_FILE=$BASE/log/toc
 EXCLUDE_FILE=$BASE/etc/exclude
+NOSNAP_FILE=$BASE/etc/nosnap
 MAIL_USERS=
 SCRIPT_BASE=$BASE/scripts
 HOSTNAME=$(hostname)
 
 function usage
 {
-	echo "USAGE: $0 [-d device]  # backup to device"
-	echo "       $0 -c           # display current log file"
+	echo "USAGE: $0 [options]"
+	echo "       -d [[user@]host:]device  # backup device"
+	echo "       -n                       # run without tape"
+	echo "       -e                       # don't eject tape"
+	echo "       -v                       # direct output to stdout"
 }
 
-while getopts cd:mr:svh c
+while getopts cd:emnr:svh c
 do
 	case $c in
 	c)	ACTION=log_view
 		;;
 	d)	DUMP_DEVICE=$OPTARG
 		;;
+	e)	NO_EJECT=1
+		;;
 	m)	MAIL_LOG=1
+		;;
+	n)	NO_TAPE=1
+		DUMP_DEVICE=/dev/null
 		;;
 	r)	RSH=$OPTARG
 		;;
@@ -52,10 +61,11 @@ shift $((OPTIND - 1))
 : ${NO_TAPE:=0}
 : ${NO_REWIND:=0}
 : ${NO_EJECT:=0}
-: ${FS_TYPES:=ufs zfs}
+: ${FSTYPES:=ufs zfs}
 : ${PAX_FORMAT:=xustar}
-: ${SNAPSHOT_ZFS:=0}
-: ${SNAPSHOT_UFS:=0}
+: ${SNAPSHOT_ZFS:=1}
+: ${SNAPSHOT_UFS:=1}
+: ${BACKING_STORE:=/var/tmp}
 : ${MAIL_LOG:=0}
 : ${MAIL_USERS:=p0073773@brookes.ac.uk}
 
@@ -73,50 +83,56 @@ if [[ -n "$REMOTE" ]]; then
 	echo $DUMP_DEVICE | sed 's/:/ /' | read DUMP_HOST DUMP_DEVICE
 fi
 
+# Print a pretty datestamp
+function datestamp
+{
+	date +'%Y-%m-%d %H:%M:%S'
+}
+
 # Check tape status
 function tape_status
 {
 	if (( NO_TAPE > 0 )); then
 		echo "--> running without tape"
+		TAPE_STATUS=$NO_TAPE
 	else
 		echo "--> checking tape status"
-		${REMOTE:+$RSH $DUMP_HOST} $MT status
+		${REMOTE:+$RSH $DUMP_HOST} $MT -f $DUMP_DEVICE status
+		TAPE_STATUS=$?
 	fi
-	NO_TAPE=$?
 }
 
 # Rewind tape
 function tape_rewind
 {
-	if (( NO_TAPE > 0 || NO_REWIND > 0 )); then
+	if (( NO_TAPE > 0 || TAPE_STATUS > 0 || NO_REWIND > 0 )); then
 		echo "--> skipped tape rewind"
 	else
 		echo "--> rewinding tape"
-		${REMOTE:+$RSH $DUMP_HOST} $MT rewind
+		${REMOTE:+$RSH $DUMP_HOST} $MT -f $DUMP_DEVICE rewind
 	fi
-	STATUS=$?
 }
 
 # Eject tape
 function tape_eject
 {
-	if (( NO_TAPE > 0 || NO_EJECT > 0 )); then
+	if (( NO_TAPE > 0 || TAPE_STATUS > 0 || NO_EJECT > 0 )); then
 		echo "--> skipped tape eject"
 	else
 		echo "--> ejecting tape"
-		${REMOTE:+$RSH $DUMP_HOST} $MT offline
+		${REMOTE:+$RSH $DUMP_HOST} $MT -f $DUMP_DEVICE offline
 	fi
-	STATUS=$?
+	return $?
 }
 
 # Write data to tape
 function tape_write
 {
-	if (( NO_TAPE > 0 )); then
+	if (( TAPE_STATUS > 0 )); then
 		echo "--> NO TAPE: piping to /dev/null"
-		cat >/dev/null
+		$DD of=/dev/null
 	else
-		${REMOTE:+$RSH $DUMP_HOST} $DD of=$DUMP_DEVICE
+		${REMOTE:+$RSH $DUMP_HOST} $DD of=$DUMP_DEVICE bs=1024
 	fi
 }
 
@@ -130,21 +146,22 @@ function toc_create
 		echo "--> exclude file not found"
 		EXCLUDE='^$'
 	fi
-	for t in $FS_TYPES; do
+	for t in $FSTYPES; do
 		$AWK -v fstype=$t -v exclude=$EXCLUDE \
 			'$3 == fstype && $2 !~ exclude {print $3, $1, $2}' \
 		< /etc/mnttab
 	done | pr -tn > $TOC_FILE
 	STATUS=$?
 	cat $TOC_FILE
+	return $STATUS
 }
 
 # Write backup ToC to dump device
 function toc_write
 {
 	echo "--> writing table of contents"
-	echo Backup of $HOSTNAME: $(date +'%Y-%m-%d %H:%M') | cat - $TOC_FILE | tape_write
-	STATUS=$?
+	echo Backup of $HOSTNAME: $(datestamp) | cat - $TOC_FILE | tape_write
+	return $?
 }
 
 # Create a snapshot of a zfs filesystem
@@ -154,11 +171,12 @@ function toc_write
 function snap_create_zfs
 {
 	HAS_SNAP=0
-	if (( SNAPSHOT_ZFS > 0 )); then
+	NOSNAP=$(echo $2 | $GREP -cF -f <(cat $NOSNAP_FILE | $GREP -v '#' | $GREP -v '^$'))
+	if (( SNAPSHOT_ZFS > 0 && $NOSNAP == 0 )); then
 		echo "--> creating zfs snapshot of $2" 1>&2
 		SNAPSHOT=$2/.zfs/snapshot/backup
 		zfs snapshot $1@backup
-		if [[ $? -eq 0 && -d $SNAPSHOT ]]
+		if [[ $? -eq 0 && -d $SNAPSHOT ]]; then
 			echo $SNAPSHOT
 			HAS_SNAP=1
 		else
@@ -170,6 +188,7 @@ function snap_create_zfs
 		echo "--> skipped creation of zfs snapshot: $2" 1>&2
 		echo $2
 	fi
+	return $HAS_SNAP
 }
 
 # Create a snapshot of a ufs filesystem
@@ -180,10 +199,10 @@ function snap_create_zfs
 function snap_create_ufs
 {
 	HAS_SNAP=0
-	if (( SNAPSHOT_UFS > 0 )); then
+	NOSNAP=$(echo $2 | $GREP -cF -f <(cat $NOSNAP_FILE | $GREP -v '#' | $GREP -v '^$'))
+	if (( SNAPSHOT_UFS > 0 && NOSNAP == 0 )); then
 		echo "--> creating ufs snapshot: $2" 1>&2
-		BACKING_STORE=$(mktemp); rm $BACKING_STORE
-		SNAPSHOT=$(fssnap -F ufs -o raw,bs=$BACKING_STORE,unlink $1)
+		fssnap -F ufs -o maxsize=512m,bs=$BACKING_STORE,unlink $2
 		if (( $? > 0 )); then
 			echo "--> ERROR: snapshot creation failed: $2" 1>&2
 			echo "--> proceeding with non-snap backup" 1>&2
@@ -195,6 +214,7 @@ function snap_create_ufs
 		echo "--> skipped creation of ufs snapshot: $2" 1>&2
 		echo $1
 	fi
+	return $HAS_SNAP
 }
 
 # Destroy the snapshot of a zfs filesystem
@@ -203,16 +223,10 @@ function snap_create_ufs
 # Result: nothing
 function snap_delete_zfs
 {
-	if (( HAS_SNAP > 0 )); then
-		echo "--> deleting zfs snapshot: $2"
-		zfs destroy -f $1@backup >/dev/null 2>&1
-		if (( $? > 0 )); then
-			echo "--> ERROR: snapshot deletion failed: $2"
-		else
-			HAS_SNAP=0
-		fi
-	else
-		echo "--> skipped deletion of zfs snapshot: $2"
+	echo "--> deleting zfs snapshot: $2"
+	zfs destroy -f $1@backup
+	if (( $? > 0 )); then
+		echo "--> ERROR: snapshot deletion failed: $2"
 	fi
 }
 
@@ -222,86 +236,57 @@ function snap_delete_zfs
 # Result: nothing
 function snap_delete_ufs
 {
-	if (( SNAPSHOT_UFS > 0 && HAS_SNAP > 0 )); then
-		echo "--> deleting ufs snapshot: $2"
-		fssnap -d $2 >/dev/null 2>&1
-		if (( $? > 0 )); then
-			echo "--> ERROR: snapshot deletion failed: $2"
-		else
-			HAS_SNAP=0
-		fi
-	else
-		echo "--> skipped deletion of ufs snapshot: $2"
-	fi
-}
-
-# Clean up snapshots on error trap
-# $1 = TYPE
-# $2 = DEVICE/FILESYSTEM
-# $3 = MOUNTPOINT
-# Result: nothing
-function snap_trap
-{
-	echo "--> trapped error..."
-	snap_delete_$1 $2 $3
-}
-
-# Dump the directory passed as argument via pax
-# $1 = SNAPSHOT
-# $2 = MOUNTPOINT
-function dump_pax
-{
-	cd $1
+	echo "--> deleting ufs snapshot: $2"
+	fssnap -d $2
 	if (( $? > 0 )); then
-		echo "==> ERROR: $1 not found, dump of $2 failed: $(date +'%Y-%m-%d %H:%M')"
-		return 1
-	fi
-	echo "==> commencing dump of $2 via pax: $(date +'%Y-%m-%d %H:%M')"
-	$PAX -w -pe -x $PAX_FORMAT -X . | tape_write
-	if (( $? > 0 )); then
-		echo "--> ERROR: dump of $2 failed: $(date +'%Y-%m-%d %H:%M')"
-	else
-		echo "--> completed dump of $2: $(date +'%Y-%m-%d %H:%M')"
-	fi
-	cd -
-}
-
-# Dump the directory passed as argument via ufsdump
-# $1 = DEVICE or SNAPSHOT
-# $2 = MOUNTPOINT
-function dump_ufsdump
-{
-	echo "==> commencing dump of $2 via ufsdump: $(date +'%Y-%m-%d %H:%M')"
-	$UFSDUMP 0uf - $1 | tape_write
-	if (( $? > 0 )); then
-		echo "--> ERROR: dump of $2 failed: $(date +'%Y-%m-%d %H:%M')"
-	else
-		echo "--> completed dump of $2: $(date +'%Y-%m-%d %H:%M')"
+		echo "--> ERROR: snapshot deletion failed: $2"
 	fi
 }
 
-# Backup a zfs filesystem
+# Dump a zfs filesystem via pax
 # $1 = FILESYSTEM
 # $2 = MOUNTPOINT
-function backup_zfs
-{
-	SNAPSHOT=$(snap_create_zfs $1 $2)
-	trap "snap_trap zfs $1 $2" 1 2 3 6 9 15
-	dump_pax $SNAPSHOT $2
-	trap - 1 2 3 6 9 15
-	snap_delete $1 $2
-}
-
-# Backup a ufs filesystem
-# $1 = DEVICE
-# $2 = MOUNTPOINT
-function backup_ufs
+function dump_zfs
 {
 	SNAPSHOT=$(snap_create_ufs $1 $2)
-	trap "snap_trap ufs $1 $2" 1 2 3 6 9 15
-	dump_ufsdump $SNAPSHOT $2
-	trap - 1 2 3 6 9 15
-	snap_delete $1 $2
+	if (( $? > 0 )); then
+		trap "snap_delete_ufs $1 $2" ERR INT EXIT
+	fi
+	cd $SNAPSHOT
+	if (( $? > 0 )); then
+		echo "==> ERROR: $SNAPSHOT not found, dump of $2 failed: $(datestamp)"
+		return 1
+	fi
+	echo "==> commencing dump of $2 via pax: $(datestamp)"
+	$PAX -w -pe -x $PAX_FORMAT -X . | tape_write
+	STATUS=$?
+	if (( STATUS > 0 )); then
+		echo "--> ERROR: dump of $2 failed: $(datestamp)"
+	else
+		echo "--> completed dump of $2: $(datestamp)"
+	fi
+	cd -
+	return $STATUS
+}
+
+# Dump a ufs filesystem via ufsdump
+# $1 = DEVICE
+# $2 = MOUNTPOINT
+function dump_ufs
+{
+	SNAPSHOT=$(snap_create_ufs $1 $2)
+	if (( $? > 0 )); then
+		trap "snap_delete_ufs $1 $2" ERR INT EXIT
+	fi
+	echo "==> commencing dump of $2 via ufsdump: $(datestamp)"
+	$UFSDUMP 0uf - $SNAPSHOT | tape_write
+	STATUS=$?
+	if (( STATUS > 0 )); then
+		echo "--> ERROR: dump of $2 failed: $(datestamp)"
+	else
+		echo "--> completed dump of $2: $(datestamp)"
+	fi
+	return $STATUS
 }
 
 # Mail interested parties
@@ -313,21 +298,21 @@ function mail_users
 # Backup all local filesystems
 function backup_all
 {
-	echo "===> Backup commenced: $(date +'%Y-%m-%d %H:%M')"
+	echo "===> Backup commenced: $(datestamp)"
 	tape_status
 	tape_rewind
 	toc_create
 	toc_write
-	while read NUM TYPE DEVICE MOUNTPOINT; do
-		backup_$TYPE $DEVICE $MOUNTPOINT
+	while read NUM FSTYPE DEVICE MOUNTPOINT; do
+		dump_$FSTYPE $DEVICE $MOUNTPOINT
 		(( STATUS > 0 )) && MAIL_LOG=1
 	done < $TOC_FILE
 	tape_eject
-	echo "===> Backup completed: $(date +'%Y-%m-%d %H:%M')"
+	echo "===> Backup completed: $(datestamp)"
 }
 
 case $# in
-0)	backup_all 2>&1 | tee -a $LOG_FILE >$OUTPUT
+0)	backup_all | tee -a $LOG_FILE >$OUTPUT
 	;;
 *)	echo "NOT IMPLEMENTED"
 	usage 1
